### PR TITLE
Change the name order and add the affiliation

### PR DESCRIPTION
**Pull request by KimSangYeon-DGU**
I changed my name order to `Sangyeon Kim` to comply with the naming convention in English.

Also, I added my affiliation. Is there any form to follow? Please let me know if I'm wrong.

### CODE REVIEW

**Comment by rcurtin** [comment]
Thanks!  Sorry I got the order wrong.  The affiliation isn't quite in the right format but I fixed it in fde2dae. :+1:

**Comment by KimSangYeon-DGU** [comment]
@rcurtin No problem! Thanks for the correction :)

**Comment by rcurtin** [comment]
@KimSangYeon-DGU also, do you have an ORCID we can add to the paper?  Thanks :)

**Comment by KimSangYeon-DGU** [comment]
@rcurtin Yes, sorry for the late update! Thanks for letting me know :)

**Pull request merged**
